POLL_TYPE_PICK_DISH = "DISH"
POLL_TYPE_QUIZ_1 = "QUIZ_1"
POLL_TYPE_QUIZ_2 = "QUIZ_2"


# Authority levels
AUTHORITY_ADMIN = 3
AUTHORITY_MODERATOR = 2
AUTHORITY_USER = 1

THANHHV3_USER_ID = 1306365691

